import type { Metadata } from "next";
import { Sour_Gummy, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const space_grotesk = Space_Grotesk({
  subsets: ["latin"],
});

const sour_gummy = Sour_Gummy({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PP Tracker",
  description: "Generated by a handsome developer",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full antialiased">
      <body className={`${space_grotesk.className} min-h-screen relative`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed inset-0 -z-10">
            <div className="absolute inset-0 bg-[linear-gradient(135deg,#0a0a0a,#000000_40%,#0a0a0a)]" />
            <div className="absolute inset-0 opacity-30 bg-[radial-gradient(circle_at_top,_rgba(255,255,255,0.08),_transparent_60%)]" />
            <div className="absolute inset-0 opacity-40 bg-[linear-gradient(to_bottom,transparent,rgba(0,0,0,0.8))]" />
          </div>

          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
