import type { Metadata } from "next";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Sour_Gummy } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider";

const sour_gummy = Sour_Gummy({
  variable: "--font-sour-gummy",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "PP Tracker",
  description: "Generated by a handsome developer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`h-full antialiased`}
    >
      <body className={sour_gummy.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
          <div className="flex min-h-screen w-full">
              <AppSidebar />
                <main className="flex-1 flex flex-col w-full">
              <Navbar />
              <SidebarTrigger />
              <div className="flex-1 flex justify-center">
                <div className="w-full max-w-6xl">{children}</div>
              </div>
            </main>
          </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
